#+title: Trackjack README
#+author: Quinn Borrok

* Project Overview

Trackjack is an extremely minimal linux-only terminal based music player. It uses its own organization method for storing lps, eps, singles, and user-created playlists. This method is largely based on my music listening needs specifically, so I would not recommend this program to everyone.

** Limitations

1. Trackjack is currently only capable of opening .flac audio files. Support will be added in the future for mp3, vorbis, opus, and raw PCM data in the form of .wav files.

2. It can also only play flac files recorded at 48000 hz. For whatever reason the flac decoding library I am using, dr_flac, will not read the sample rate of a file. So, I have to assume it to be 48000. If you try playing a file that is not 48000 hz, it will play at an incorrect speed. You can solve this by using the following ffmpeg command to change the sample rate of the audio:

#+BEGIN_SRC sh
ffmpeg -i input_file.flac -ar 48000 output_file.flac
#+END_SRC

This will also be fixed in the future. I plan to switch to ffmpeg's avcodec instead of the simpler but more limited dr_flac.

3. Trackjack is also currently incapable of switching audio devices. To create the openAL context in which audio is played, I use the alutInit() function, which is part of the apparently largely deprecated openAL utility toolkit library. This function automatically assumes which device to bind to, and I have not yet implemented a way to change it.

4. Trackjack is currently built to work in a specific size of terminal. If you would like it to be smaller you can change the macros around in screen.c and see what happens. In the future I will have trackjack either automatically fit itself into the window size its currently in, or add much better methods to control window size during compilation.

** Features

1. Play music


** Build instructions

1. Ensure you have the following programs installed: git, gcc, make
2. Ensure you have the following libraries installed: openAL, ncurses

3. Download trackjack's source code and navigate to its folder:
   #+BEGIN_SRC sh
   git clone https://github.com/konkonkonk/trackjack
   cd trackjack
   #+END_SRC

4. To compile:
   #+BEGIN_SRC sh
   make
   #+END_SRC
   To compile and install:
   (IMPORTANT: When you run trackjack this way, it will not be able to navigate to the test home directory packaged in the source code. You will have to load a home directory via a command at runtime, or by editing the init() function in src/trackjack.c before compilation.)
   #+BEGIN_SRC sh
   sudo make install
   #+END_SRC
